package com.fm.exchange.model

data class Rates(
	val cHF: Double? = null,
	val hRK: Double? = null,
	val mXN: Double? = null,
	val zAR: Double? = null,
	val iNR: Double? = null,
	val cNY: Double? = null,
	val tHB: Double? = null,
	val aUD: Double? = null,
	val iLS: Double? = null,
	val kRW: Double? = null,
	val jPY: Double? = null,
	val pLN: Double? = null,
	val gBP: Double? = null,
	val iDR: Double? = null,
	val hUF: Double? = null,
	val pHP: Double? = null,
	val tRY: Double? = null,
	val rUB: Double? = null,
	val hKD: Double? = null,
	val iSK: Double? = null,
	val dKK: Double? = null,
	val cAD: Double? = null,
	val mYR: Double? = null,
	val uSD: Double? = null,
	val bGN: Double? = null,
	val nOK: Double? = null,
	val rON: Double? = null,
	val sGD: Double? = null,
	val cZK: Double? = null,
	val sEK: Double? = null,
	val nZD: Double? = null,
	val bRL: Double? = null
)
